In [2]:
import numpy as np

In [3]:
array = np.array([1,2,3,4])

In [4]:
array

array([1, 2, 3, 4])

In [5]:
two_d_array = np.array([[1,2,3],[4,5,6]])

In [9]:
two_d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
array.shape

(4,)

In [11]:
two_d_array.shape

(2, 3)

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones(4)

array([1., 1., 1., 1.])

In [31]:
numpy1= np.ones((2,3))

In [32]:
numpy1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.random.rand(5)

array([0.80076426, 0.31305693, 0.05679809, 0.50371396, 0.02526579])

In [40]:
np.random.rand(1,3)

array([[0.88268603, 0.11957376, 0.07607255]])

In [45]:
np.random.randint(1,10,5)

array([6, 9, 6, 9, 7], dtype=int32)

In [62]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a*2)
print(b*2)
print(a*b)

[20 40 60]
[2 4 6]
[10 40 90]


In [85]:
array = np.array([10,20,30,40])

In [87]:
np.std(array)

np.float64(11.180339887498949)

In [88]:
#LESSION 2 ____________________

In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
arr

array([10, 20, 30, 40, 50, 60])

In [147]:
arr[1:4]     # elements at index 1,2,3      # whole array


array([20, 30, 40])

In [148]:
arr[:3]

array([10, 20, 30])

In [98]:
arr[:]

array([10, 20, 30, 40, 50, 60])

In [149]:
arr[::-1]

array([60, 50, 40, 30, 20, 10])

In [155]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [156]:
m[0,1]

np.int64(2)

In [110]:
m[2,2]

np.int64(9)

In [157]:
m[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [65]:
mike = np.array([10, 20, 30, 40, 50, 60,70])

In [44]:
mike[mike>30]

array([40, 50, 60, 70])

In [31]:
mike[mike%20==0]

array([20, 40, 60])

In [45]:
mike[[0, 4, 5]]

array([10, 50, 60])

In [46]:
mike[0]=100

In [64]:
mike

array([ 0, 20, 50, 50, 50,  0,  0])

In [48]:
mike[2:4] = 50

In [66]:
mike

array([10, 20, 30, 40, 50, 60, 70])

In [67]:
mike[mike>50] = 0

In [68]:
mike

array([10, 20, 30, 40, 50,  0,  0])

In [158]:
a = np.array([10, 30, 45, 70, 90, 20, 65])

In [159]:
a[(a<30)&(a>70)]=-1

In [3]:
#fancy indexing

In [5]:
arr = np.array([10,20,30,40,50,60])

In [8]:
arr[[0,3,5]]

array([10, 40, 60])

In [9]:
arr[(arr > 20) & (arr < 60)]

array([30, 40, 50])

In [11]:
arr[2:8][arr[2:8] > 50]

array([60])

In [16]:
arr = np.array([10,20,30,40,50,60])

In [18]:
arr[2:8][arr[2:8] > 50]

array([60])

In [19]:
arr = np.array([10,20,30,40,50,60,70,80,90])

In [20]:
arr[2:8][arr[2:8] > 50]

array([60, 70, 80])

In [12]:
arr = np.array([5, 12, 25, 40, 55, 68, 72, 81])

In [25]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

In [14]:
arr = np.array([5, 10, 15, 20, 25, 30])

In [15]:
arr[2:6][arr[2:6]<25]

array([15, 20])

In [46]:
m = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [48]:
m

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [25]:
m[:, [0, 2]]

array([[10, 30],
       [40, 60],
       [70, 90]])

In [26]:
m[m > 50]

array([60, 70, 80, 90])

In [35]:
m[0:2, :][m[0:2, :] > 25]

array([30, 40, 50, 60])

In [51]:
m[m[:, 0] > 30]

array([[40, 50, 60],
       [70, 80, 90]])

In [58]:
m[m[:,1] % 2 == 0]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [136]:
m = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])

In [208]:
m

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [143]:
m[:,0:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [145]:
m[:,[0,2]]

array([[ 5, 15],
       [20, 30],
       [35, 45]])

In [146]:
# part 3 of lesson 3 in numpy

In [192]:
arr = np.array([1,2,3,4,5,6])

In [161]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [193]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [165]:
arr

array([1, 2, 3, 4, 5, 6])

In [194]:
arr.ravel()

array([1, 2, 3, 4, 5, 6])

In [176]:
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [196]:
array=(1,1,3)

In [209]:
amm=np.array([[[[1,2,3]]]])

In [211]:
np.squeeze(amm)

array([1, 2, 3])

In [212]:
arr = np.array([10,20,30,40,50,60])